# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
